#!/usr/bin/env ruby


# ──────────────────────────────────────────────────────────── Configuration ──┐
ROOT_DIR = File.dirname(File.expand_path(__FILE__))

$:.unshift ROOT_DIR
require "sfw"

SCRIPTS_DIR = ROOT_DIR.to_pn.join("scripts")
DEST_DIR    = (ENV["CHIPS_DST_DIR"] || "/usr/local/bin").to_pn
# ─────────────────────────────────────────────────────────────────────────────┘

# ──────────────────────────────────────────────────────────────────── Utils ──┐
def copy_chips(category)
  Pathname.glob(SCRIPTS_DIR.join(category.to_s).join("*")) do |chip_src_path|
    "installing chip `#{chip_src_path.basename.as_tok}`..".pinf
    chip_dst_path = DEST_DIR.join(chip_src_path.basename(chip_src_path.extname))
    chip_src_path.build_script to: chip_dst_path
  end
end
# ─────────────────────────────────────────────────────────────────────────────┘

# ────────────────────────────────────────────────────────────── Entry Point ──┐
categories = Pathname.glob(SCRIPTS_DIR.join("*")).map do |category_path|
  category_path.basename.to_s
end

options = parse_args do |parser, opts|
  parser.on("-c", "--categories x,y,z", Array, "categories to include") do |cat|
    opts[:categories] = cat
  end
end

selected_categories = if options[:categories]
                        options[:categories]
                      else
                        "asking for selected categories..".pinf
                        categories.select do |category|
                          "include #{category}".ask type: :bool
                        end
                      end

ensure_root unless $simulate

if "performing setup of categories: `#{selected_categories}`. are you sure".ask
  selected_categories.each { |category| copy_chips category }
end
# ─────────────────────────────────────────────────────────────────────────────┘


# vim: set filetype=ruby :
