#!/usr/bin/env ruby


def exec_cmd()

def compile(kernel_dir)
  FileUtils.cd(kernel_dir) do
    system("make")
  end
end

def compile(kernel_dir)
  FileUtils.cd(kernel_dir) do
    system("make")
  end
end

cd "/usr/src/linux"
echo $EUID
echo ">> Compiling.."
make

echo ">> Installing kernel modules.."
make modules_install

echo ">> Installing the kernel image.."
make install

echo ">> Creating the initramfs.."
dracut --force initrd-`uname -r`


# vim: set filetype=ruby :
