#!/usr/bin/env zsh


# {{{ Parse options.

zparseopts -A _opts -without-sync

_with_sync=$([ -z "${(k)_opts[--without-sync]}" ] && echo 1 || echo 0)

# }}}

if [[ ${_with_sync} -ne 0 ]]; then
  echo "<< Repositories synchronization."
  echo "Yes" | eix-sync -q
fi

echo "<< Updates installation."
echo "Yes" | emerge --update --newuse --deep --with-bdeps=y @world @system

echo "<< Cleaning unused dependencies."
echo "Yes" | emerge --depclean

echo "<< Rebuilding reverse dependencies."
echo "Yes" | revdep-rebuild

if [[ -x /usr/sbin/python-updater ]]; then
  echo "<< Updating python packages."
  echo "Yes" | python-updater
fi

if [[ -x /usr/sbin/haskell-updater ]]; then
  echo "<< Updating haskell packages."
  echo "Yes" | haskell-updater
fi

if [[ -x /usr/sbin/perl-cleaner ]]; then
  echo "<< Rebuilding perl packages."
  perl-cleaner --all
fi

echo "<< System update finished."


# vim: set filetype=zsh :
