#!/usr/bin/env zsh


# {{{ Configuration.

typeset -A _workspaces
_workspaces=(
  ref 0 wflow_0 1 wflow_1 2 wflow_supp_0 3 wflow_supp_1 4 org 5
  social 6 mgmt 7 tmp 8
)
_initial_workspace_name="ref"

_user_email=`git config --get user.email`
if [[ -z "${_user_email}" ]]; then
  notify-send "skipping startup" "invalid git user.email configuration"
  exit -1
fi

# }}}

# {{{ Prompt for login.

lpass login "${_user_email}"
lpass sync
if [[ $? -eq 0 ]]; then
  _logged_in=1
else
  _logged_in=0
fi

# }}}

# {{{ SSH key

if [[ -f "${HOME}/.ssh/id_rsa" ]]; then
  ssh-add "${HOME}/.ssh/id_rsa"
fi

# }}}

if [[ ${_logged_in} -ne 0 ]]; then
  # {{{ Open `social` software.

  openterm --title "mutt" --cmd "mutt" &
  openterm --title "weechat" --cmd "weechat" &
  openterm --title "turses" --cmd "turses" &

  # }}}

  # {{{ Open `org` software.

  openterm --title "taskwarrior" --cmd "task list" &

  # }}}

  # {{{ Open `ref` software.

  chromium-browser &
#  firefox &

  # }}}

  openterm --title "anapnea" --cmd "ssh alem0lars@anapnea.net" &
fi


# vim: set filetype=zsh :
